from __future__ import annotations

"""报告治理场景的可选 LLM Reviewer。

这个模块把模型审阅限制在“辅助意见”角色：它可以补充确定性规则不容易发现的
论证问题、表达问题和风险提示，但不能直接决定任务是否 passed / failed。
调用方应把返回值保存为 LLMReviewArtifact，并由确定性 evaluator 保持最终裁决。
"""

import json
import re
import sys
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field


REPO_ROOT = Path(__file__).resolve().parents[4]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
load_dotenv(REPO_ROOT / ".env", override=True)

from common.llm_factory import build_llm, resolve_provider_config  # noqa: E402


class LLMReviewResult(BaseModel):
    """Structured auxiliary review generated by an LLM."""

    verdict: str = Field(description="approve / caution / reject")
    confidence: float = Field(ge=0.0, le=1.0)
    strengths: list[str] = Field(default_factory=list)
    concerns: list[str] = Field(default_factory=list)
    suggested_actions: list[str] = Field(default_factory=list)
    raw_text: str = ""


class ReportLLMReviewer:
    """Small wrapper around the repository-level LLM provider factory."""

    def __init__(self, *, provider: str | None = None, model_name: str | None = None) -> None:
        self.provider_config = resolve_provider_config(provider=provider, model_name=model_name)
        self.llm = build_llm(provider=provider, model_name=model_name, temperature=0.1, json_mode=True)

    def review(self, *, markdown: str, metrics: dict[str, Any], issues: list[dict[str, str]]) -> LLMReviewResult:
        system_prompt = (
            "你是 Agent Runtime 报告治理场景中的辅助审阅员。"
            "确定性规则已经完成评分，你不能改写最终 passed/failed。"
            "你的任务是补充内容质量、证据边界、论证完整性和潜在风险意见。"
            "只返回 JSON，不要返回 Markdown。"
        )
        user_prompt = (
            "请审阅以下 Markdown 报告，并严格返回 JSON：\n"
            "{\n"
            '  "verdict": "approve 或 caution 或 reject",\n'
            '  "confidence": 0到1之间的小数,\n'
            '  "strengths": ["优点"],\n'
            '  "concerns": ["问题或风险"],\n'
            '  "suggested_actions": ["建议动作"]\n'
            "}\n\n"
            f"确定性指标：{json.dumps(metrics, ensure_ascii=False)}\n"
            f"确定性问题：{json.dumps(issues, ensure_ascii=False)}\n"
            f"报告正文：\n{markdown[:7000]}"
        )
        response = self.llm.invoke(
            [
                SystemMessage(content=system_prompt),
                HumanMessage(content=user_prompt),
            ]
        )
        return parse_llm_review(str(response.content))

    @property
    def provider(self) -> str:
        return self.provider_config.name

    @property
    def model(self) -> str:
        return self.provider_config.model


def parse_llm_review(raw_text: str) -> LLMReviewResult:
    """Parse an LLM review JSON response with a small extraction fallback."""
    text = _extract_json(raw_text)
    try:
        result = LLMReviewResult.model_validate_json(text)
    except Exception:
        result = LLMReviewResult.model_validate(json.loads(text))
    return result.model_copy(update={"raw_text": raw_text})


def _extract_json(text: str) -> str:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    return match.group(0) if match else text
